### PR TITLE
Updated the versions of the dependencies.

### PR DESCRIPTION
**Pull request by AdityaD16**

### CODE REVIEW

**Comment by veds12** [comment]
@AdityaD16 one of the checks seems to be failing. Seems like a numpy version problem. Can you downgrade numpy to a version below?

**Comment by AdityaD16** [comment]
> @AdityaD16 one of the checks seems to be failing. Seems like a numpy version problem. Can you downgrade numpy to a version below?

Yea I downgraded to previous version which supports python 3.7

**Comment by veds12** [comment]
There's a problem with another dependency. Are you running pre-commit before pushing?

**Comment by AdityaD16** [comment]
> There's a problem with another dependency. Are you running pre-commit before pushing?

Yes all tests passed. I will downgrade scipy and pytest to original versions also.

**Pull request merged**
