### PR TITLE
 Add a task dataset class and a task sampler

### LINKED ISSUE #24: Add a task dataset class and a task sampler
Thanks for suggesting @AnirudhM1 and @Devanshu42 !

- We can follow the same structure as learn2learn's [TaskDataset](http://learn2learn.net/docs/learn2learn.data/#learn2learn.data.task_dataset.TaskDataset).
- Number of ways and shots can be passed as parameters to the TaskDataset

### PR DESCRIPTION
**Pull request by eigengravy**
Closes #24

### CODE REVIEW

**Comment by veds12** [comment]
@eigengravy Can you please add docstrings to the code?
Also, according to my understanding (please correct me if I am wrong), this dataset and task sampler will work with torch tensors, i.e. it will output datapoints in the form of torch tensors. 

We should create separate Dataset and Samplers that can work with jax numpy arrays. See for eg:

https://jax.readthedocs.io/en/latest/notebooks/Neural_Network_and_Data_Loading.html#data-loading-with-pytorch

**Comment by eigengravy** [comment]
Added docstrings.
Changed tasks from pytorch tensors to jax numpy arrays.
Added iterator in `TaskDataset`.

Should tasks as pytorch tensors be retained?

**Comment by veds12** [comment]
@eigengravy tasks should also be converted to jax tensors. Basically the dtype which the networks can take as input

**Comment by eigengravy** [comment]
@veds12 `TaskDataset.sample()` does return `List[Tuple[jnp.ndarray, int]]`

**Comment by veds12** [comment]
Okay. I didn't understand this then:

> Should tasks as pytorch tensors be retained?

**Comment by eigengravy** [comment]
I was wondering if a `sample_as_pytorch_tensor` method is required

**Comment by veds12** [comment]
Not required for now

**Review by veds12 — APPROVED** [review]

**Pull request merged**
