### PR TITLE
Added Automatic Changelog Generator

### PR DESCRIPTION
**Pull request by arihantbansal**
Used [generate-changelog](https://github.com/marketplace/actions/generate-changelog). 

Updates changelog upon:

1. Pull Request closed
2. Release published
3. Issue edited or closed

Solves #2.

### CODE REVIEW

**Comment by veds12** [comment]
@arihantbansal have you tried running this locally? You can create dummy branches in your own fork and open (& merge) a PR from one to another and see if it generates a changelog

**Comment by arihantbansal** [comment]
> @arihantbansal have you tried running this locally? You can create dummy branches in your own fork and open (& merge) a PR from one to another and see if it generates a changelog

I did and it seems to run but I'm unable to locate the file where it generated the changelog. I'm looking into it.

**Comment by veds12** [comment]
The changelog is generated in the temp workspace and is discarded once the workflow finishes running unless you commit and push the generated changelog. See this: 
https://github.com/ERC-BPGC/handbook/blob/084127d2b341cb8a05b015601afe16e54ac07ce9/.github/workflows/changelog_update.yml#L20

Also, once done, please squash all the commits into one

**Comment by arihantbansal** [comment]
Thanks, got it. I've updated the settings. It should work now.

**Pull request merged**
