### PR TITLE
Add tests 

### PR DESCRIPTION
**Pull request by Riddhi2587**
Tests for maml and optimization trainer

### CODE REVIEW

**Comment by veds12** [comment]
@Riddhi2587 please run the pre-commit before pushing:
https://github.com/SforAiDl/jeta/blob/main/CONTRIBUTING.md

**Comment by abhi-glitchhg** [comment]
@Riddhi2587, Were you trying to update your branch with the new changes? If yes, git force is not a proper way to do it. 

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

@veds12, can you check with repository settings if the following option is available?
 `Always suggest updating pull request branches.` 
updating branches would be more easy.

**Comment by veds12** [comment]
@abhi-glitchhg Yeah she did it by mistake. Luckily the the commit was empty. I have disabled pushing to the main repo directly (requires permit from one of the maintainers after an approved review)

**Comment by abhi-glitchhg** [comment]
> I have disabled pushing to the main repo directly (requires a permit from one of the maintainers after an approved review)

Nice. 

But I was suggesting a different thing; If you enable it; collaborators and maintainers can easily update the branches.
here's  [github documentation](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-suggestions-to-update-pull-request-branches) of the feature. 

IMO it is a good to have in this repo as well. 

if there is conflict it shows up there as well. 

(reference image)
image

**Pull request merged**
