### PR TITLE
Added ANIL Algorithm.

### LINKED ISSUE #27: Algorithm Implementation: Almost No Inner Loop (ANIL)
Paper Link: https://arxiv.org/abs/1909.09157

This can also be added as an extension to MAML

### PR DESCRIPTION
**Pull request by AdityaD16**
Closes #27

### CODE REVIEW

**Comment by AdityaD16** [comment]
closes #27

**Comment by veds12** [comment]
@AdityaD16 have you run this implementation on any dataset?

**Comment by AdityaD16** [comment]
> @AdityaD16 have you run this implementation on any dataset?

Yes I did that.

**Comment by veds12** [comment]
What dataset? And how's the performance?

**Comment by AdityaD16** [comment]
> What dataset? And how's the performance?

Omniglot dataset. I was not able to check the accuracy but the loss values were similar when using maml.py present in the repo. I also made sure that parameters of all but last layer were not updating.

I will fix the pre-commit issue and re-commit.

**Comment by veds12** [comment]
@AdityaD16 is this ready to merge? (it's still a draft)

**Comment by AdityaD16** [comment]
> @AdityaD16 is this ready to merge? (it's still a draft)

Yea its ready to merge now

**Review by veds12 — APPROVED** [review]

**Pull request merged**
